### PR TITLE
Added Decentralized Graffiti Drawing Tool Demo link

### PR DESCRIPTION
**Pull request by VGR-GIT**
As requested by GreyWizard, he wanted to include the matching video of his 'Decentralized Graffiti Drawing' tool.

```
Section: Community - Tools
Item: Decentralized Graffiti Drawing Tool
Action: Add/Edit/Delete
```

**By submitting this pull request, I promise I've read the [contribution guidelines](https://github.com/isidorosp/awesome-rocketpool/blob/master/CONTRIBUTING.md).**

### CODE REVIEW

**Comment by isidorosp** [comment]
Since we already have a link to the tool, why not include the video in the same line?

**Comment by VGR-GIT** [comment]
Currently, things are grouped on a specific category (guides, video, ...) There is already an item covering the same topic, but it's situated as a guide because it's a written article, so I thought I'd put this under the video section. 

If you still think this should be referenced in the same line (Community - Guides), let me know, otherwise I propose we put this under the 'Community - Videos' section.

**Comment by isidorosp** [comment]
> Currently, things are grouped on a specific category (guides, video, ...) There is already an item covering the same topic, but it's situated as a guide because it's a written article, so I thought I'd put this under the video section.
> 
> If you still think this should be referenced in the same line (Community - Guides), let me know, otherwise I propose we put this under the 'Community - Videos' section.

The issue I see with this approach is a) you end up with duplicated content (or potentially even more, as you might have a video, an article, a tool, all referring to the same thing), and b) you end up with content that refers to the same "thing" spread across different parts of the page. From a user perspective, I think it makes more sense if they see e.g. a tool and then right next to it a video related to the tool, as opposed to having to see where on the page there may or may not be a related video/article/whatever. In general, is the issue with grouping items by medium instead of by content.

@0xpenguin0x what do you think?

**Comment by VGR-GIT** [comment]
No longer valid; this was included/fixed in the pull request that fixed/changed the subcategories/sections. (https://github.com/isidorosp/awesome-rocketpool/tree/VGR-GIT-Categorize-Subcategories-By-Content-Instead-Of-Medium)

**Pull request closed without merging**
